# Generated by Django 5.1 on 2024-09-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField()),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('order_type', models.CharField(max_length=10)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('original_position_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('symbol', models.CharField(max_length=8)),
                ('opening_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('closing_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('commission_usd', models.DecimalField(decimal_places=4, max_digits=5)),
                ('swap_usd', models.DecimalField(decimal_places=3, max_digits=3)),
                ('profit_usd', models.DecimalField(decimal_places=3, max_digits=7)),
                ('equity_usd', models.CharField(max_length=10)),
                ('margin_level', models.CharField(max_length=10)),
                ('close_reason', models.CharField(max_length=10)),
            ],
        ),
    ]
