# Generated by Django 5.1 on 2024-09-10 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0003_accountbalance_profits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='profits',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
