# Generated by Django 5.1 on 2024-09-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0004_processedprofit_remove_accountbalance_profits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='profits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
