# Generated by Django 5.1 on 2024-09-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0005_accountbalance_profits'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeframe', models.CharField(max_length=50)),
                ('indicators', models.CharField(blank=True, max_length=200, null=True)),
                ('average_duration', models.DurationField(blank=True, null=True)),
                ('backtesting_perfomance', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='planned_R_Multiple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='profit_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='stop_loss_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='ticket',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='tradesmodel',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexJournal.strategymodel'),
        ),
    ]
