# Generated by Django 5.1 on 2024-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0006_strategymodel_tradesmodel_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymodel',
            name='market_conditions',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='strategymodel',
            name='risk_management',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='strategymodel',
            name='rules_follow',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
