# Generated by Django 5.1 on 2024-11-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0012_alter_mt5login_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesmodel',
            name='lot_size',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='original_position_size',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
