# Generated by Django 5.1 on 2024-11-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0015_alter_tradesmodel_profit_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='is_default_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='profit_target',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='stop_loss_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
