# Generated by Django 5.1 on 2024-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0016_accountbalance_is_default_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
