# Generated by Django 5.1 on 2024-12-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0017_alter_accountbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesmodel',
            name='closing_price',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='commission_usd',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='lot_size',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='opening_price',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='original_position_size',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='planned_R_Multiple',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='profit_usd',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='stop_loss',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='swap_usd',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
        migrations.AlterField(
            model_name='tradesmodel',
            name='take_profit',
            field=models.DecimalField(decimal_places=7, max_digits=25),
        ),
    ]
