# Generated by Django 5.1 on 2025-07-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexJournal', '0018_alter_tradesmodel_closing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesmodel',
            name='ticket',
            field=models.BigIntegerField(unique=True),
        ),
    ]
